//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkV1_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public byte[] Image { get; set; }
        public decimal MinPrice { get; set; }
        public Nullable<decimal> RealPrice { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public string IdWin { get; set; }
        public bool IsActive { get; set; }
    }
}
